apiVersion: v1
kind: Secret
metadata:
  name: se-postgres
  namespace: default
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXNfdXNlcg== # base64 encoded value of 'postgres_user'
  POSTGRES_PASSWORD: c2VjdXJlX3Bhc3N3b3Jk # base64 encoded value of 'secure_password'
