version: "3.76"

services:
  symfony:
    container_name: equest_symfony
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/www/app
    depends_on:
      - database
    networks:
      - symfony_network

  database:
    container_name: equest_database
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: equest
      POSTGRES_PASSWORD: equest
      POSTGRES_USER: equest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d equest -U equest"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    restart: always
    networks:
      - symfony_network

  frontend:
    container_name: equest_frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"

networks:
  symfony_network:
    driver: bridge

volumes:
  database_data:
