apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-traefik
  namespace: kube-public
  labels:
    app: traefik
subjects:
  - kind: ServiceAccount
    name: sa-traefik
    namespace: kube-public
roleRef:
  kind: ClusterRole
  name: rbac-traefik
  apiGroup: rbac.authorization.k8s.io
