version: "3.7"

services:
  # php-fpm:
  #   container_name: php-fpm
  #   build:
  #     context: ./tools/docker/php-fpm
  #   depends_on:
  #     - database
  #   environment:
  #     - APP_ENV=${APP_ENV}
  #     - APP_SECRET=${APP_SECRET}
  #     - DATABASE_URL=${DATABASE_URL}
  #   volumes:
  #     - ./../src/:/var/www

  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ./nginx
  #   volumes:
  #     - ./../src/:/var/www
  #     - ./tools/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./tools/docker/nginx/sites/:/etc/nginx/sites-available
  #     - ./tools/docker/nginx/conf.d/:/etc/nginx/conf.d
  #     - ./logs:/var/log
  #   depends_on:
  #     - php-fpm
  #   ports:
  #     - "80:80"
  #     - "443:443"

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: equest
      POSTGRES_PASSWORD: equest
      POSTGRES_USER: equest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d equest -U equest"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    restart: always
  ###< doctrine/doctrine-bundle ###

networks:
  symfony_network:
    driver: bridge

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
